### PR TITLE
Dockerdev: Upgrade PostgreSQL from version 11 to 13

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by Envek** [comment]
But why not [13](https://www.postgresql.org/about/news/2077/)? :smile:

Also interesting question here is data migration: you can't just change RDBMS major version, you also need upgrade data. For example with `pg_upgrade` (which requires both old and new versions). Or not migrate but rather drop database volume and resetup the database. But it's offtopic for this particular example, of course: it is not meant to cover all possible cases.

**Comment by oliverklee** [comment]
Oh, I wasn't aware that version 13 already is available. :-)

I'll update the PR accordingly.

**Comment by oliverklee** [comment]
Done and repushed.

**Comment by Envek** [comment]
Thank you!

As a note: in your project you also need to bump docker image version to force its rebuild with newer client libraries.

Excerpt from [our blog post](https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development#app):
> You only need to upgrade the local image version every time you make changes to it (or **to the arguments** or files it relies on).

**Pull request merged**
