### PR TITLE
Determine Debian release name automatically 

### LINKED ISSUE #11: PostGIS
How would one go about including PostGIS with this setup?

I tried adding: 
```
postgresql-11-pgrouting
postgresql-11-pgrouting-scripts
postgresql-11-postgis-2.5
postgresql-11-postgis-2.5-scripts
```

To both my `Aptfile` and my `Dockerfile` (in 2 different tries), none of which worked.
IIRC, Postgres now carries the PostGIS package in its apt repository. But yet I'm getting `Unable to locate package postgresql-11-postgis-2.5` when I run `docker-compose build`.

Any thoughts?

### PR DESCRIPTION
**Pull request by sponomarev**
Determine Debian release name automatically for the right PostgreSQL source in development Dockerfile.

Fixes #11

### CODE REVIEW

**Review by palkan — APPROVED** [review]
👏

**Comment by Envek** [comment]
Also in Debian and derivatives there is special command for that:

```sh
lsb_release --short --codename
```

**Comment by bibendi** [comment]
We faced this problem in the latest project, but in my opinion, it's better to use a specific version of the image. Otherwise, we have to put that hack to every other custom library that will tend to the mess in Dockerfile.

image

**Comment by palkan** [comment]
> `lsb_release --short --codename`

```
E: The repository 'http://apt.postgresql.org/pub/repos/apt -pgdg Release' does not have a Release file.
Error executing command, exiting
```

🤷🏻‍♂️

**Comment by sponomarev** [comment]
It isn’t  installed by default

**Comment by sponomarev** [comment]
@bibendi i don’t see a problem with that.

**Comment by Envek** [comment]
Ouch! Yes, it seems to be so: http://affy.blogspot.com/2014/11/is-using-lsbrelease-cs-good-idea-inside.html

**Pull request merged**
